dist: trusty
language: node_js
cache: yarn
node_js:
  - '8'
install:
- yarn install --frozen-lockfile
after_failure:
- yarn build -- --inspect
script:
- yarn lint
- yarn build
- yarn coverage # This runs the tests and generates coverage data
after_success: npm run coveralls # It expects "coverage" to run first
